### ISSUE TITLE
OSM Analytics Next Steps

### ISSUE THREAD

**Issue by cgiovando** [hotosm/osm-analytics#53]
*A tentative summary of the [Aug 18 community meeting](https://gitter.im/hotosm/osm-analytics/archives/2016/08/18) on Gitter. Please add anything that I might have missed or any other idea in the comments. Thanks!*

# Priorities / Top Ideas

- Include **more map tags/features** for processing and display
- Improve **[OSMA Cruncher](https://github.com/hotosm/osm-analytics-cruncher/) efficiency**
- Find alternate **hosting of processed tiles** products
- **Thematic analysis**, for example to measure progress of mapping projects in achieving SDGs for specific areas (e.g. spatial distribution of schools, financial services, or drinking water points)
- Integrate **@jenningsanderson's work** http://mapbox.github.io/osm-analysis-collab/
- improve **feature summaries** for defined AOIs to be more accurate . Compare @sabas's [osm-estratti](http://osm-estratti.wmflabs.org/estratti/Liguria) vs. buildings and km of roads for the [same area](http://osm-analytics.org/#/show/polygon:gezv%40_mpmGwk%5Dz%5EujbBzuq%40slEmfH%7B%7CS~%7CKkyUc%60IvxN_DxvA%7DgKrfTwhDbaEmnQbsk%40cu%5Cpp%5Bpo%40q_ByoZtwm%40%7BtIhrUdvFbsa%40%7DqQr~IlrEy%5EdxOrwKkh%40ntJh%60MdfMcrPli~%40zoTlp%5BoaHhnAnnQtmZzmTraApp_%40%7CvTlgGfhi%40_%7DCy%7BB~gG%60aq%40f%7Ch%40kqFdbPo%7CWza%40cgmAeuTa%7DS%7BtKuhRa%60b%40sj%5CcqJklHisSuyq%40y%7CV/highways/recency) (Liguria) in OSM Analytics.

# Tasks

- [ ] @tyrasd to host a code walk-through with interested developers and complete #44 
- [ ] @rodowi to explore methods for parallelizing cruncher processing and send PR
- [ ] @jenningsanderson to work with MapBox team to integrate osm-analysis-collab
- [ ] @giovand draft work plan for development of thematic analysis and additional map features
- [ ] @sabas to research methods for improving summaries accuracy, send PR
- [ ] @lukasmartinelli document steps on how to submit PR for adding features to OSMA cruncher

# Other Ideas

- option to **switch background layer** (e.g. imagery or other OSM renderings) with opacity controls
- Add functions to **identify gaps** in map by use of machine learning and satellite imagery. See #43 
- Develop an **alert mechanism** that checks for any processing issues. See #49 
- Integrate **@lukasmartinelli's osm-activity** https://github.com/lukasmartinelli/osm-activity
- Simple drop-down select tool to allow **authenticated users to add data processing** for any tag, similar to how Export Tools work (e.g. house numbers, road types, etc)
- Improve the **visualization of shadowed edits** (80% of user edits are shadowed according to @jenningsanderson). Also http://mapbox.github.io/osm-analysis-collab/shadowed-edits
- Develop **documentation and demos** (videos? dedicated docs? overlaid tips?)
- Develop a **visual/guided query builder** for the less experienced users
- Increase resolution of **density grid to be more detailed** a lower Z levels. See [#21](https://github.com/hotosm/osm-analytics/issues/21#issuecomment-218615611). Also consider @lukasmartinelli's approach of using points at low zoom levels and then switching to polygons at higher levels.
- find options to have a **more detailed before/after history**. Maybe having monthly snapshots in addition to yearly (as of now) to start.
- consider the idea of running on-demand **crunching jobs for smaller AOIs** to increase frequency or specific requests by users, without having to run the entire planet.
- **Integration with other OSM tools** (to-fix, MapRoulette, etc) to allow users quick editing/fixing capabilities when they notice some issues. See #38 
- link OSMA and Export Tools to allow users to **download data** of areas that are analyzing
- improve region simplification. See #51 
- Load region/AOI from URL in GeoJSON format. See #6

**Comment by lukasmartinelli** [comment]
> @lukasmartinelli document steps on how to submit PR for adding features to OSMA cruncher

Totally didn't follow up on this - sorry. Hope to free up some time to help in the future.
